### ISSUE TITLE
Data Missing from Repo

### ISSUE THREAD

**Issue by calvinjlin** [intelligent-environments-lab/utx000#23]
I do not see the data folder in GitHub. You may want to check the .gitignore.

https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/.gitignore#L78-L79

**Comment by HagenFritz** [comment]
data folder is included in the gitignore and I am storing things on my machine locally. Some of the data in that directory contains sensitive information and since GH is not HIPPA-compliant, I cannot have the data available here. I will just have to send you the data periodically.

**Comment by calvinjlin** [comment]
21, 41, 48, 46, 11

**Comment by HagenFritz** [comment]
Uploaded what data I have to UT Box for those 5 beacons

**Comment by HagenFritz** [comment]
Added BPEACE2 EMA surveys

**Comment by HagenFritz** [comment]
Added BPEACE2 GPS data

**Comment by HagenFritz** [comment]
More data will be provided on an "as-needed" basis
