### ISSUE TITLE
Extensive Use of User Specific Paths

### ISSUE THREAD

**Issue by calvinjlin** [intelligent-environments-lab/utx000#24]
None of these paths will work on another person's machine. All folders referenced in the path must exist in the repo or someone else who copies and run this repo will run into errors. I didn't check the 2.0 and older notebooks, but I assume the problem also exists there. There is also room for improvement in terms of assigning redundant strings to variables and also centralizing the paths in one place rather than having them scattered throughout the file (this would have also made it easier to fix this file path problem in the first place).

https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L53
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L100
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L123
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L127
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L146
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L156-L157
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L179-L180
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L206
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L321
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L494
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L502
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/data/make_dataset.py#L670
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L44
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L78
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L104
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L114
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L142
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L173
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L187
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L214
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L242
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L248
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L255
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L263
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L268-L269
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L422
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L440
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/src/reports/make_report.py#L445-L446
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.2.1-hef-fitbit-exploration-processing.ipynb#L54
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.2.1-hef-fitbit-exploration-processing.ipynb#L1198
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.2.1-hef-fitbit-exploration-processing.ipynb#L1210
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.0-hef-sleep-distributions.ipynb#L201
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.0-hef-sleep-distributions.ipynb#L359
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.0-hef-sleep-distributions.ipynb#L568
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.0-hef-scd30-check.ipynb#L88-L90
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/4.0-hef-scd30-check.ipynb#L97-L99
https://github.com/intelligent-environments-lab/utx000/blob/master/notebooks/4.0-hef-beacon-op-check.ipynb
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-rem2nrem-outcome-exploration.ipynb#L40
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-rem2nrem-outcome-exploration.ipynb#L71
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-rem2nrem-outcome-exploration.ipynb#L103
https://github.com/intelligent-environments-lab/utx000/blob/master/notebooks/3.0-hef-bivar-regression-exploration.ipynb
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-efficiency-outcome-exploration.ipynb#L40
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-efficiency-outcome-exploration.ipynb#L272
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/3.0-hef-bivar-efficiency-outcome-exploration.ipynb#L304
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/2.0-hef-weather-patterns.ipynb#L148
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/2.0-hef-qual-vs-quant-sleep.ipynb#L261
https://github.com/intelligent-environments-lab/utx000/blob/e077a24768cc1a78321b903ecb5c593e7fff7fce/notebooks/2.0-hef-qual-vs-quant-sleep.ipynb#L291-L294

**Comment by calvinjlin** [comment]
@HagenFritz

**Comment by HagenFritz** [comment]
Yeah a lot of these are old and quite frankly not worth the time to fix. I am not necessarily trying to make this repo available for anyone else to use either. I will correct a few of these, but I don't anticipate using anything from the ut1000 or ut2000 classes anytime soon.

**Comment by HagenFritz** [comment]
Fixed all user-specific paths in the src files except for any references to my dissertation external hard drive. This path is an input to the processing functions, so users can define their own path if need be. 

Notebooks with user-specific paths have been archived.
