### ISSUE TITLE
Study notes and data exploration

### ISSUE THREAD

**Issue by HagenFritz** [intelligent-environments-lab/utx000#43]
# Understanding the UTx000 Study
As a starting point, you should review the IRB for the study (see the UT box folder) to understand what kind of measures we want to take and for what purpose.

From there, take a look at the somewhat out-dated [data dictionary](https://github.com/intelligent-environments-lab/utx000/blob/master/references/data_dictionaries/Codebook%20-%20Data%20Dictionary%20-%20UTx000.xlsx) that I recently uploaded. Most of the variables were still gathered during this most recent cohort.

**Comment by calvinjlin** [comment]
Which one is the IRB?

**Comment by HagenFritz** [comment]
Not sure if I have access to the actual IRB docs, but I just uploaded the study consent form which gives a decent enough overview. I can always fill in gaps if you have any questions. see [here](https://github.com/intelligent-environments-lab/utx000/blob/master/references/utx000ext_admin/utx000_consent_form.pdf)

**Comment by HagenFritz** [comment]
Let me know if you have any further questions.

**Comment by HagenFritz** [comment]
Let me know if you have any further questions.
