### ISSUE TITLE
Constructor calls means that these files are required

### ISSUE THREAD

**Issue by calvinjlin** [intelligent-environments-lab/utx000#44]
Not really sure we need to fix this, but I thought I should point it out. Since these files are referenced in the constructors, which are called before any user input is requested, then these files are mandatory for running the script.

https://github.com/intelligent-environments-lab/utx000/blob/3cdf85ea908082a0b15086146739dce6002e9a89/src/data/make_dataset.py#L1177-L1181
https://github.com/intelligent-environments-lab/utx000/blob/3cdf85ea908082a0b15086146739dce6002e9a89/src/data/make_dataset.py#L215-L218
https://github.com/intelligent-environments-lab/utx000/blob/3cdf85ea908082a0b15086146739dce6002e9a89/src/data/make_dataset.py#L623-L626

**Comment by HagenFritz** [comment]
Calvin, yeah I noticed that too. That explains why you needed that file because the bpeace() call was newly added.
