### ISSUE TITLE
Better file formats than csv for intermediate and processed data

### ISSUE THREAD

**Issue by calvinjlin** [intelligent-environments-lab/utx000#66]
Currently, all data is stored as csv files. While this can be beneficial for opening in excel or sharing, binary file formats tend to perform better in read/save speed as well as file size. For saving processed beacon data, this can be the difference between taking >100 seconds to save for a csv or 3-20 seconds (varies with compression) for a binary file format like parquet. This topic may be worth considering further if performance optimizations are desired in the future.

https://towardsdatascience.com/the-best-format-to-save-pandas-data-414dca023e0d
![image](https://user-images.githubusercontent.com/58328424/109760872-1534a200-7bb5-11eb-842f-01ba973eea3e.png)
![image](https://user-images.githubusercontent.com/58328424/109760973-43b27d00-7bb5-11eb-93b3-103c77fd50c1.png)

**Comment by HagenFritz** [comment]
While I think there is value in what your are proposing here, I have a few issues with it:
* the load and save times for the intermediate and processed data have never been an issue  - < 10 seconds at the most
* the processed datafiles are the once that are most likely to be shared with others. The time we get from saving in a file format like .feather might be counteracted by the fact that if we want to share the data, we have to convert it into a file format people are comfortable with i.e. .csv
* there is a lot of existing code that is based around csv data files.
